[package]
name = "rust_bridge_ixi_test2"
version = "0.1.0"
authors = ["Alex6323 <Al3k5@protonmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
prost = "0.5.0"
bytes = "0.4.12"
byteorder = "1.3.1"

[build-dependencies]
prost-build = "0.5.0"
which = "2.0.1"
